# Generated by Django 5.0.6 on 2024-06-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionshop', '0002_rename_nome_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
